// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDevice() {
  return window['go']['main']['App']['ConnectDevice']();
}

export function LogPrint(arg1) {
  return window['go']['main']['App']['LogPrint'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function ScreenShot() {
  return window['go']['main']['App']['ScreenShot']();
}

export function StartClick(arg1, arg2) {
  return window['go']['main']['App']['StartClick'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
