// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {click} from '../models';

export function ConnectDevice():Promise<void>;

export function LogPrint(arg1:Array<any>):Promise<void>;

export function Pause():Promise<click.ClickStatus>;

export function Resume():Promise<click.ClickStatus>;

export function ScreenShot():Promise<string>;

export function StartClick(arg1:Array<click.Point>,arg2:click.Params):Promise<void>;

export function Status():Promise<click.ClickStatus>;

export function Stop():Promise<click.ClickStatus>;
